# Generated by Django 3.0.3 on 2020-02-20 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('owned_by', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('active_on', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
