# Generated by Django 3.0.3 on 2020-02-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_on',
        ),
    ]
