# Generated by Django 3.0.3 on 2020-02-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_active_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='INR', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owned_by',
            field=models.CharField(default=None, max_length=100, verbose_name='Owner'),
        ),
    ]
